import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={inter.className + ' h-full'}>
        <div className="h-full bg-black w-full flex items-center justify-center">
          <div className="h-3/4 w-1/2 rounded-lg border bg-black text-card-foreground shadow-sm overflow-hidden">
            <Header />

            <div className='pt-8 px-10 max-h-[85%] overflow-hidden'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
